### ISSUE TITLE
remove allocations + optimize them

### ISSUE THREAD

**Issue by matu3ba** [liquidaty/zsv#2]
For better performance you want to remove allocations and store the state (ie string escaped or not etc) on the stack, if possible.
Check the file size to estimate, if allocation is necessary.

Also: I dont see that you use arena allocation. Did I miss that?

**Comment by liquidaty** [comment]
We were of the same thinking initially, and our first (unreleased) zsv version used `alloca` and other means to allocate on the stack instead of heap for the parser state memory. To our surprise, the benchmark figures showed no material improvement, so we decided against it to keep the code simple and more portable, and to allow for higher limits for certain options that impact memory usage.

If there is evidence that may contradict our findings and that would suggest that changing its current heap calls to stack would have a material impact on performance, we'd be happy to review it and reconsider. The best form of that evidence would be a pull request accompanied by some benchmark figures, but we'd be happy to look at other forms
